"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const full=fs.readFileSync(path.join(__dirname,"../src/script.04.jeu-pokedex.js"),"utf8"),start=full.indexOf("let dailyRequestInFlight = null;"),end=full.indexOf("function surrenderGame()",start);
assert.ok(start>=0&&end>start);const source=full.slice(start,end),DAY="2026-10-02";
function response(data,status=200){return {ok:status>=200&&status<400,status,json:async()=>data};}function snapshot(names,finished=false){return {ok:true,day:DAY,accountId:"A",attempts:names.length,guessed:names,finished};}
function fixture(){const nodes=new Map();let wins=0,renders=0,error="",timeoutFn=null,calls=0;function node(id){if(!nodes.has(id)){const classes=new Set();nodes.set(id,{value:"Pikachu",innerHTML:"",textContent:"",focus(){},classList:{add:c=>classes.add(c),remove:c=>classes.delete(c),contains:c=>classes.has(c),toggle(c,on){on?classes.add(c):classes.delete(c);}}});}return nodes.get(id);}
 const env={window:{__pokedleAuthed:true,addEventListener(){}},connectedAccountUser:{id:"A"},gameMode:"daily",gameOver:false,attempts:0,guessedNames:[],guessedSet:new Set(),resultHistory:[],POKEMON_LIST:[{id:1,name:"Bulbizarre"},{id:25,name:"Pikachu"}],
 document:{getElementById:node},readJson:()=>({dailyKey:DAY}),STORAGE_KEYS:{dailyGame:"daily"},getUTCDateKey:()=>DAY,findPokemon:name=>env.POKEMON_LIST.find(p=>p.name===name),compare:()=>({}),addRow(){},saveCurrentGame(){},saveDailyResult(){},clearSavedGame(){},
 renderGameOverBox(){renders++;},getTodayDailyResult:()=>null,playerStats:{lastDailyWinKey:null},winRegisteredForCurrentGame:false,guessCache:new Map(),LIVE_RANK_CACHE:new Map([["daily",{}]]),updateSilhouettePanel(){},updatePixelPanel(){},showErr:v=>{error=v;},clearErr:()=>{error="";},showWin:()=>{wins++;},
 AbortController,setTimeout:fn=>{timeoutFn=fn;return 1;},clearTimeout:()=>{timeoutFn=null;},fetch:async()=>{calls++;return response(snapshot(["Pikachu"]));}};env.secretPokemon=env.POKEMON_LIST[0];vm.createContext(env);vm.runInContext(source,env);
 return {env,node,get wins(){return wins;},get renders(){return renders;},get error(){return error;},get calls(){return calls;},timeout(){timeoutFn?.();}};}
test("Daily suppresses double submit and preserves text typed while waiting",async()=>{const f=fixture();let resolve,posts=0;f.env.fetch=()=>{posts++;return new Promise(r=>resolve=r);};const a=f.env.submitGuess(),b=f.env.submitGuess();assert.equal(posts,1);f.node("guess-input").value="Bulbizarre";resolve(response(snapshot(["Pikachu"])));await a;await b;assert.equal(f.env.attempts,1);assert.equal(f.node("guess-input").value,"Bulbizarre");});
test("lost winning response restores result without another local award",async()=>{const f=fixture();f.node("guess-input").value="Bulbizarre";f.env.fetch=async()=>{throw Error("lost");};await f.env.submitGuess();f.env.fetch=async()=>response({...snapshot(["Bulbizarre"],true),ok:false,error:"daily_finished"},409);await f.env.submitGuess();assert.equal(f.env.attempts,1);assert.equal(f.wins,0);assert.equal(f.renders,1);assert.equal(f.env.gameOver,true);});
test("fresh successful win awards exactly once",async()=>{const f=fixture();f.node("guess-input").value="Bulbizarre";f.env.fetch=async()=>response({...snapshot(["Bulbizarre"],true),correct:true,ranked:true});await f.env.submitGuess();assert.equal(f.wins,1);await f.env.submitGuess();assert.equal(f.wins,1);});
test("duplicate response reconstructs the missing row",async()=>{const f=fixture();f.env.fetch=async()=>response({...snapshot(["Pikachu"]),ok:false,error:"duplicate_guess"},409);await f.env.submitGuess();assert.equal(f.env.attempts,1);assert.equal(f.env.resultHistory.length,1);});
for(const [name,change] of Object.entries({mode:f=>f.env.gameMode="normal",account:f=>f.env.connectedAccountUser={id:"B"},round:f=>f.env.resultHistory=[],surrender:f=>f.env.gameOver=true,navigation:f=>f.node("screen-game").classList.add("hidden"),midnight:f=>f.env.getUTCDateKey=()=> "2026-10-03"})){test("late response cannot mutate after "+name,async()=>{const f=fixture();let resolve;f.env.fetch=()=>new Promise(r=>resolve=r);const pending=f.env.submitGuess();change(f);resolve(response({...snapshot(["Bulbizarre"],true),correct:true}));await pending;assert.equal(f.env.attempts,0);assert.equal(f.wins,0);assert.equal(f.renders,0);});}
test("malformed/stale snapshots never partially mutate state",async()=>{for(const data of [{...snapshot(["Pikachu"]),accountId:"B"},{...snapshot(["Pikachu"]),day:"2026-10-03"},{...snapshot(["Pikachu"]),attempts:2},snapshot(["MissingNo"]),snapshot(["Pikachu"],true)]){const f=fixture();f.env.fetch=async()=>response(data);await f.env.submitGuess();assert.equal(f.env.attempts,0);assert.equal(f.env.resultHistory.length,0);assert.ok(f.error);}});
test("timeout releases guard and retry succeeds",async()=>{const f=fixture();f.env.fetch=(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener("abort",()=>reject(Error("timeout"))));const p=f.env.submitGuess();f.timeout();await p;f.env.fetch=async()=>response(snapshot(["Pikachu"]));await f.env.submitGuess();assert.equal(f.env.attempts,1);});
test("session resume restores authoritative history without a guess",async()=>{const f=fixture();let url,body;f.env.fetch=async(u,o)=>{url=u;body=JSON.parse(o.body);return response(snapshot(["Pikachu"]));};await f.env.syncDailyObservedState();assert.equal(url,"/api/daily/session");assert.equal(body.day,DAY);assert.equal(body.accountId,"A");assert.equal(f.env.attempts,1);});
test("old Daily is never submitted under a new UTC day",async()=>{const f=fixture();f.env.readJson=()=>({dailyKey:"2026-10-01"});await f.env.submitGuess();assert.equal(f.calls,0);assert.equal(f.env.attempts,0);});
test("guest Daily and other solo modes keep local gameplay",async()=>{for(const mode of ["daily","normal","silhouette","pixel","cry","mystery"]){const f=fixture();f.env.gameMode=mode;f.env.window.__pokedleAuthed=false;f.node("guess-input").value="Bulbizarre";await f.env.submitGuess();assert.equal(f.env.attempts,1);assert.equal(f.wins,1);assert.equal(f.calls,0);}});
test("start/restore reconcile and surrender is guarded",()=>{const starts=fs.readFileSync(path.join(__dirname,"../src/script.02.statclash.js"),"utf8"),saves=fs.readFileSync(path.join(__dirname,"../src/script.07.delegation-party.js"),"utf8");assert.match(starts,/function startDailyGame\(\)[\s\S]*syncDailyObservedState\(\)/);assert.match(saves,/function restoreSavedGame\([\s\S]*if \(gameMode === "daily"\) syncDailyObservedState\(\)/);assert.match(full,/function surrenderGame\(\)[\s\S]*gameMode === "daily" && dailyRequestInFlight/);});
